export const CHARACTER_LIST_REQUEST = 'CHARACTER_LIST_REQUEST'
export const CHARACTER_LIST_SUCCESS = 'CHARACTER_LIST_SUCCESS'
export const CHARACTER_LIST_FAIL = 'CHARACTER_LIST_FAIL'

export const CHARACTER_DETAILS_REQUEST = 'CHARACTER_DETAILS_REQUEST'
export const CHARACTER_DETAILS_SUCCESS = 'CHARACTER_DETAILS_SUCCESS'
export const CHARACTER_DETAILS_FAIL = 'CHARACTER_DETAILS_FAIL'

export const EPISODE_BRBA_REQUEST = 'EPISODE_BRBA_REQUEST'
export const EPISODE_BRBA_SUCCESS = 'EPISODE_BRBA_SUCCESS'
export const EPISODE_BRBA_FAIL = 'EPISODE_BRBA_FAIL'

