export const CHARACTER_LIST_REQUEST = 'CHARACTER_LIST_REQUEST'
export const CHARACTER_LIST_SUCCESS = 'CHARACTER_LIST_SUCCESS'
export const CHARACTER_LIST_FAIL = 'CHARACTER_LIST_FAIL'

export const CHARACTER_DETAILS_REQUEST = 'CHARACTER_DETAILS_REQUEST'
export const CHARACTER_DETAILS_SUCCESS = 'CHARACTER_DETAILS_SUCCESS'
export const CHARACTER_DETAILS_FAIL = 'CHARACTER_DETAILS_FAIL'

export const EPISODE_BRBA_REQUEST = 'EPISODE_BRBA_REQUEST'
export const EPISODE_BRBA_SUCCESS = 'EPISODE_BRBA_SUCCESS'
export const EPISODE_BRBA_FAIL = 'EPISODE_BRBA_FAIL'

export const EPISODE_BCS_REQUEST = 'EPISODE_BCS_REQUEST'
export const EPISODE_BCS_SUCCESS = 'EPISODE_BCS_SUCCESS'
export const EPISODE_BCS_FAIL = 'EPISODE_BCS_FAIL'

export const RANDOM_QUOTE_REQUEST = 'RANDOM_QUOTE_REQUEST'
export const RANDOM_QUOTE_SUCCESS = 'RANDOM_QUOTE_SUCCESS'
export const RANDOM_QUOTE_FAIL = 'RANDOM_QUOTE_FAIL'


